"""empty message

Revision ID: 1e89e03b9bed
Revises: 5f2b50859f60
Create Date: 2026-03-09 00:09:06.464926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e89e03b9bed'
down_revision: Union[str, Sequence[str], None] = '5f2b50859f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('languages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('submission_batches', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('submissions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'updated_at')
    op.drop_column('submission_batches', 'updated_at')
    op.drop_column('languages', 'updated_at')
    op.drop_column('languages', 'created_at')
    # ### end Alembic commands ###
